name: Terraform Destroy (Amsa)

# Allows manual trigger from GitHub UI
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # 3️⃣ Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 4️⃣ Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # 5️⃣ Terraform Destroy
      - name: Terraform Destroy
        working-directory: terraform
        run: |
          echo "✅ Destroying Terraform resources..."
          terraform destroy -auto-approve -var-file="terraform.tfvars"

      # 6️⃣ Success message
      - name: Destroy Complete
        run: echo "✅ All Terraform resources have been destroyed."
